# Generated by Django 5.2.3 on 2025-09-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_question_employeequestionresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
