# Generated by Django 5.2.3 on 2025-09-02 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_employee_comments_employee_employee_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='comments',
        ),
        migrations.CreateModel(
            name='DepartmentEmployeeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_comments', to='app1.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_comments', to='app1.employee')),
            ],
            options={
                'unique_together': {('employee', 'department')},
            },
        ),
    ]
