# Generated by Django 5.2.3 on 2025-09-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_employee_comments_departmentemployeecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentemployeecomment',
            name='department_head_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_concerned_question',
            field=models.BooleanField(default=False),
        ),
    ]
