# Generated by Django 5.2.3 on 2025-09-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_departmentemployeecomment_department_head_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_assigned_department',
            field=models.BooleanField(default=False),
        ),
    ]
